### ISSUE TITLE
build fail on ubuntu 16.04 with lib4cplus 1.2.1

### ISSUE THREAD

**Issue by bjamet** [hove-io/navitia#2166]
I try to compile the navitia project. I installed all the dependencies and passed the "./configure" step. 
But during the "make" step I have errors about lib4cplus : 
```
../../fare/libfare.a(fare.cpp.o) : Dans la fonction « log4cplus::detail::macros_get_logger(log4cplus::Logger&&) » :
/usr/local/include/log4cplus/loggingmacros.h:106 : référence indéfinie vers « log4cplus::Logger::Logger(log4cplus::Logger&&) »
/usr/local/include/log4cplus/loggingmacros.h:106 : référence indéfinie vers « log4cplus::Logger::Logger(log4cplus::Logger&&) »
/usr/local/include/log4cplus/loggingmacros.h:106 : référence indéfinie vers « log4cplus::Logger::Logger(log4cplus::Logger&&) »
collect2: error: ld returned 1 exit status
```
I don't know if this is due to the version of lib4cplus, or to the compilation since the issue occurs on a "#if defined" scope 
```
$cat /usr/local/include/log4cplus/loggingmacros.h
[...]
#if defined (LOG4CPLUS_HAVE_RVALUE_REFS)
inline
Logger
macros_get_logger (Logger && logger)
{
    return std::move (logger);
}

#endif
[...]
```
Thank you for the help

**Comment by antoine-de** [comment]
yes unfortunatly the log4cplus library on ubuntu 16.04 has not been correctly compiled (no c++11 flags 😢 )

it has been referenced here #1781 
the solution is to take another version of the library's package (I think I have the 1.0.4v5)

**Comment by bjamet** [comment]
Thank you, I'm building the dependencies, so I corrected it using 
```
CXXFLAGS=-std=c++11 ./configure
```
on lib4cplus. 
But I have still other problem with protobuf 3.3 : 
```
../kraken/libfill_disruption_from_database.a(fill_disruption_from_database.cpp.o) : Dans la fonction « google::protobuf::internal::ArenaStringPtr::SetNoArena(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) » :
/usr/local/include/google/protobuf/arenastring.h:215 : référence indéfinie vers « google::protobuf::internal::fixed_address_empty_string[abi:cxx11] »
```
and pqxx : 
```
usr/local/lib/libpqxx.a(connection_base.o) : Dans la fonction « pqxx::connection_base::backendpid() const » :
/[...]/libpqxx-3.0.3/src/connection_base.cxx:146 : référence indéfinie vers « PQbackendPID »
```
If you can help me again. thank you

**Comment by TeXitoi** [comment]
Same thing for protobuf: you need a c++11 compiled library.

For pqxx, I think you need at least v4.0. Here, I have:

$ apt-cache policy libpqxx-dev
libpqxx-dev:
  Installed: 4.0.1+dfsg-3
  Candidate: 4.0.1+dfsg-3
  Version table:
 *** 4.0.1+dfsg-3 0
        990 http://ftp.fr.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status

________________________________
De : bjamet [notifications@github.com]
Envoyé : mardi 1 août 2017 12:31
À : CanalTP/navitia
Cc : Subscribed
Objet : Re: [CanalTP/navitia] build fail on ubuntu 16.04 with lib4cplus 1.2.1 (#2166)


Thank you, I'm building the dependencies, so I corrected it using

CXXFLAGS=-std=c++11 ./configure


on lib4cplus.
But I have still other problem with protobuf 3.3 :

../kraken/libfill_disruption_from_database.a(fill_disruption_from_database.cpp.o) : Dans la fonction « google::protobuf::internal::ArenaStringPtr::SetNoArena(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) » :
/usr/local/include/google/protobuf/arenastring.h:215 : référence indéfinie vers « google::protobuf::internal::fixed_address_empty_string[abi:cxx11] »


and pqxx :

usr/local/lib/libpqxx.a(connection_base.o) : Dans la fonction « pqxx::connection_base::backendpid() const » :
/[...]/libpqxx-3.0.3/src/connection_base.cxx:146 : référence indéfinie vers « PQbackendPID »


If you can help me again. thank you

**Comment by bjamet** [comment]
Thank you again,
I can build navitia now, but the test with jormungandr fails. 
```
61/66 Test: jormungandr
=================================== FAILURES ===================================
_________________________ make_url_date_and_count_test _________________________

    def make_url_date_and_count_test():
        synthese = Synthese(id='tata', timezone='UTC', service_url='http://bob.com/')
    
        url = synthese._make_url(MockRoutePoint(route_id='route_tata', line_id='line_toto', stop_id='stop_tutu'),
                                 count=2, from_dt=_timestamp("12:00"))
    
        # it should be a valid url
>       assert validators.url(url)
E       assert ValidationFailure(func=url, args={'public': False, 'value': u'http://bob.com/?SERVICE=tdg&roid=stop_tutu&rn=2&date=2016-02-07 12:00'})
E        +  where ValidationFailure(func=url, args={'public': False, 'value': u'http://bob.com/?SERVICE=tdg&roid=stop_tutu&rn=2&date=2016-02-07 12:00'}) = <function url at 0x7f5472a65de8>('http://bob.com/?SERVICE=tdg&roid=stop_tutu&rn=2&date=2016-02-07 12:00')
E        +    where <function url at 0x7f5472a65de8> = validators.url

../../source/jormungandr/jormungandr/realtime_schedule/tests/synthese_test.py:62: AssertionError
==================== 1 failed, 327 passed in 14.26 seconds ===================
```
the url failed to be valid. Seams valid for me, maybe this a problem with 'validators' version
pip show validators
Name: validators
Version: 0.12.0

Moreover for 
63/66 Test: jormungandr_integration_tests
I have several connexion error. 
Do I need to set up a database for these tests ?

**Comment by antoine-de** [comment]
hum strange, did you install the requirements in `source/jormungandr/requirements_dev.txt` ?

**Comment by bjamet** [comment]
I though I did, but not. 
jormungandr and jormungandr_serpy Pass now. 
but jormungandr_integration_tests and jormungandr_serpy_integration_tests still fail.
Do I need to set up a database for these tests ?

**Comment by antoine-de** [comment]
nop no other setup is needed, but for the tests that fail (the integration tests), you need to build navitia (to have some mock kraken executables)

how do you run the tests ?
can you tell us what error you have ?

**Comment by bjamet** [comment]
Ok, sorry, I didn't install rabbitMQ nor redis. 
Everythink works now. 
Thank you  very much for your help
